baseURL = "https://jonghyun-yun.github.io/procmod"
languageCode = "en-us"

title = "procmod"
theme = "hugo-theme-learn"
RelativeURLs=true
CanonifyURLs=true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  pygmentsCodeFences = true
  pygmentsStyle="monokai"
    editURL = ""
  author = "jonghyun-yun"
  description = "Documentation for procmod"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = true
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = "green"

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/jonghyun-yun/procmod"
  weight = 10
